{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "redis-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "redis-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "redis-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "redis-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
